spring:
  datasource:
    username: root
    password: 'fuGe123.Shuai'
    url: jdbc:mysql://127.0.0.1:3306/hrtftest?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver